name: Docker Image CI

on:
  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.1
      with:
        repository: lua-cometa/test_git
        run-id: 1694381448

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        username: cometa22
        password: ${{secrets.DOCKERHUB_ACCESS_TOKEN }}
    
    - name: Build the Docker image
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        file: ./build/container/Dockerfile
        push: true
        tags: cometa22/test:0.0.1-b
